### ISSUE TITLE
Vue使用状态机解析path路径的疑问

### ISSUE THREAD

**Issue by youngwind** [banama/aboutVue#3]
hi, banama：
我看了你的[这篇文章](https://github.com/banama/aboutVue/blob/master/pathStateMachine.md)，收获良多，谢谢！
但是，有一些地方我没有想明白。
**1. 为什么Vue要使用状态机来解析path路径？**
比如你在文章中举的例子

```
var a = {
    b: {
        c: {
            d: "e"
        }
    }
}
var path = "b.c.d"
```

如果仅仅是想得到path路径对应的值，那么直接根据path拼接一个新的Function不是一个更简单的方法吗？示意代码如下：

```
new Function(scope){
   return scope.b.c.d
}
```

这也是Vue源码中[makeGetterFn函数](https://github.com/vuejs/vue/blob/e7932f80eeacf6f7d392bf520e98c4790db9d5c1/src/parsers/expression.js#L139)所干的事情。

所以，**使用状态机解析path有什么特别的优势吗？**

**2. 如何触发状态机**
我自己做的例子是这样的：

```
<div id="demo">
    <p>{{user.info[1].name}}</p>
    <p>{{user.age}}</p>
</div>
```

但是发现整个程序执行下来，**根本不会触发[parse/path.js里面的parsePath函数](https://github.com/vuejs/vue/blob/e7932f80eeacf6f7d392bf520e98c4790db9d5c1/src/parsers/path.js#L262)，更加谈不上使用状态机解析path路径了。**
相反，程序触发的是[parse/expression.js里面的parseExpression函数](https://github.com/vuejs/vue/blob/e7932f80eeacf6f7d392bf520e98c4790db9d5c1/src/parsers/expression.js#L193)。

我想知道要**怎样编写demo才能触发parse/path.js里面的parsePath函数呢？**因为不触发它，我根本没有办法debug状态机这一部分的代码。

**Comment by banama** [comment]
不好意思，回复的有点晚。
1  直接根据path拼接一个新的Function是一个更简单的方法，但是这种方法只能取值，如makeGetterFn, parsePath主要用在[compileSetter](https://github.com/vuejs/vue/blob/e7932f80eeacf6f7d392bf520e98c4790db9d5c1/src/parsers/expression.js#L204-L210)  -> setPath ->  parsePath
2  如1中所说的，parsePath 主要用在 compileSetter， 具体体现在双向绑定，比如｀v-model` 指令，入口在[这里](https://github.com/vuejs/vue/blob/e7932f80eeacf6f7d392bf520e98c4790db9d5c1/src/watcher.js#L59)

**Comment by youngwind** [comment]
@banama 好的，我再去看一下，谢谢！
